name: Build Bitmapflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev libclang-dev clang pkg-config
        
    - name: Install Rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
        rustup toolchain install nightly
        rustup default nightly
        
    - name: Setup OpenCV
      run: |
        echo "OpenCV_DIR=/usr/lib/x86_64-linux-gnu/cmake/opencv4" >> $GITHUB_ENV
        
    - name: Build Rust library
      run: |
        cd rust
        cargo build --release
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bitmapflow-rust-lib
        path: rust/target/release/
